version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - content-service
      - recommendation-service

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - kafka
      - mongo-user
    environment:
      MONGO_URL: mongodb://mongo-user:27017/users
      KAFKA_BROKER: kafka:9092

  content-service:
    build: ./content-service
    ports:
      - "3002:3002"
    depends_on:
      - kafka
      - mongo-content
    environment:
      MONGO_URL: mongodb://mongo-content:27017/content
      KAFKA_BROKER: kafka:9092

  recommendation-service:
    build: ./recommendation-service
    ports:
      - "3003:3003"
    depends_on:
      - kafka
      - mongo-reco
    environment:
      MONGO_URL: mongodb://mongo-reco:27017/reco
      KAFKA_BROKER: kafka:9092

  mongo-user:
    image: mongo
    ports:
      - "27018:27017"

  mongo-content:
    image: mongo
    ports:
      - "27019:27017"

  mongo-reco:
    image: mongo
    ports:
      - "27020:27017"
